### ISSUE TITLE
Count estimate

### ISSUE THREAD

**Issue by kjetilk** [phochste/AtteanX-Store-LDF#1]
Hi!

I just looked through the code, and I think there is a small problem with the implementation of counts. 

There's also a nuance in the API that probably needs to be looked at.
[Attean::API::TripleStore](https://metacpan.org/source/GWILLIAMS/Attean-0.007/lib/Attean/API/Store.pm#L42) has both a method ```count_triples_estimate``` and ```count_triples``` where the latter has to be exact, while the former can be an estimate. 

In [the TPF spec](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#metadata) void:triples is the required property to have in there, but that is also specified to be an estimate, so I think ```count_triples_estimate``` is the method that should be implemented. 

If you can also implement ```count_triples``` that'd be a bonus, but it means that it has to be based on something that is known to be exact. And I'm not sure hydra:totalItems is that. I posted something [about that](https://lists.w3.org/Archives/Public/public-hydra/2014Oct/0048.html), but I don't know if the semantics has been resolved. 

So, actually, my suggestion would be to implement ```count_triples_estimate``` now, like you have but based on void:triples, and leave ```count_triples``` to use the default implementation.

CC @RubenVerborgh @lanthaler @kasei

Cheers,

Kjetil

**Comment by RubenVerborgh** [comment]
Indeed; the only prerequisite is that the estimate must be non-zero if and only if the number of matching triples is.

**Comment by kjetilk** [comment]
Ah, indeed this is solved and can be closed.
